### ISSUE TITLE
apiVersion mismatch between last-applied-configuration and manifest causes silent import failure

### ISSUE THREAD

**Issue by willthames** [kbst/terraform-provider-kustomization#121] opened 2021-08-31 07:07 UTC
If you have a resource that appears to be apps/v1 but was last applied with extensions/v1beta1, terraform import fails silently 

This came up for me today with a (very old) Deployment but will likely come up again for Ingress

This would be fine if it failed with an error message but it says it imported successfully but `terraform state list` doesn't have it there. 

I suspect that erroring if the `lac` has a differnt api version to the response resource in https://github.com/kbst/terraform-provider-kustomization/blob/master/kustomize/resource_kustomization.go#L484-L491 might be enough for this edge case

**Comment by pst** [comment] 2021-09-29 13:45
I agree it shouldn't fail silently. I'm not sure about the cause. A diff between the apiVersion in the ID given to the import command and what's in the lastAppliedConfig annotation seems most likely to cause this.

Relying on the annotation is generally a problem with the provider. Linking this here to connect the dots to consider for a future refactor. https://github.com/kbst/terraform-provider-kustomization/pull/89

**Comment by pst** [comment] 2023-01-03 14:06
This issue hasn't had any activity in a long time and the code has since been refactored. I'm closing this issue. Should the issue show up again, we can create a new issue.

**Closed by pst** 2023-01-03 14:06 UTC
Labels: bug
