### ISSUE TITLE
getOriginalModifiedCurrent failed: unexpected end of JSON input

### ISSUE THREAD

**Issue by sirlori** [kbst/terraform-provider-kustomization#136] opened 2021-10-06 17:14 UTC
I don't know what exactly is causing this, but with this Service:
```
kubectl get service  appsmith-editor -o json -n appsmith 
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"name\":\"appsmith-editor\",\"namespace\":\"appsmith\"},\"spec\":{\"ports\":[{\"port\":80,\"targetPort\":80}],\"selector\":{\"app\":\"appsmith-editor\"}}}\n"
        },
        "creationTimestamp": "2021-08-16T18:08:24Z",
        "managedFields": [
            {
                "apiVersion": "v1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:kubectl.kubernetes.io/last-applied-configuration": {}
                        }
                    },
                    "f:spec": {
                        "f:ports": {
                            ".": {},
                            "k:{\"port\":80,\"protocol\":\"TCP\"}": {
                                ".": {},
                                "f:port": {},
                                "f:protocol": {},
                                "f:targetPort": {}
                            }
                        },
                        "f:selector": {
                            ".": {},
                            "f:app": {}
                        },
                        "f:sessionAffinity": {},
                        "f:type": {}
                    }
                },
                "manager": "terraform-provider-kustomization_v0.5.0",
                "operation": "Update",
                "time": "2021-08-16T18:08:24Z"
            }
        ],
        "name": "appsmith-editor",
        "namespace": "appsmith",
        "resourceVersion": "88786750",
        "selfLink": "/api/v1/namespaces/appsmith/services/appsmith-editor",
        "uid": "6aa54af8-f63f-42df-a5de-5899f609ede8"
    },
    "spec": {
        "clusterIP": "172.20.13.41",
        "ports": [
            {
                "port": 80,
                "protocol": "TCP",
                "targetPort": 80
            }
        ],
        "selector": {
            "app": "appsmith-editor"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

corresponding to the following kustomize yaml: 
```
apiVersion: v1
kind: Service
metadata:
  name: appsmith-editor
spec:
  selector:
    app: appsmith-editor
  ports:
  - port: 80
    targetPort: 80
```

I can't successfully run a terraform plan because of this error:
```
│ Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceDiff: apiVersion: "v1", kind: "Service", namespace: "appsmith" name: "appsmith-editor": getOriginalModifiedCurrent failed: unexpected end of JSON input
│ 
│   with module.webservices_cluster_k8s_base_deploy_appsmith.kustomization_resource.appsmith["~G_v1_Service|appsmith|appsmith-editor"],
│   on ../common/base_k8s_deployments/appsmith/appsmith.tf line 40, in resource "kustomization_resource" "appsmith":
│   40: resource "kustomization_resource" "appsmith" {
```

So then I modified [this](https://github.com/kbst/terraform-provider-kustomization/blob/f90ba7f8ee9da8a66c2205c28cb91a1d08e1c3a9/kustomize/util.go#L38)  part of the code like this and rebuild the provider and used `terraform init -plugin-dir=` to run it:
```
       client := m.(*Config).Client
        cgvk := m.(*Config).CachedGroupVersionKind

        n, err := parseJSON(modifiedJSON)
        if err != nil {
                log.Printf("JSONERRORmod: %v %v", modifiedJSON, err)
                return nil, nil, nil, err
        }
        o, err := parseJSON(originalJSON)
        if err != nil {
                log.Printf("JSONERRORor: %v %v", originalJSON, err)
                return nil, nil, nil, err
        }

        setLastAppliedConfig(o, originalJSON)
        setLastAppliedConfig(n, modifiedJSON)
```

In the terraform apply output I can se the following:
```
  26097,108: 2021-10-06T18:22:53.966+0200 [DEBUG] provider.terraform-provider-kustomization_v0.5.0: 2021/10/06 18:22:53 JSONERRORmod:  unexpected end of JSON input
  26104,108: 2021-10-06T18:22:54.138+0200 [DEBUG] provider.terraform-provider-kustomization_v0.5.0: 2021/10/06 18:22:54 JSONERRORmod:  unexpected end of JSON input
  26124,108: 2021-10-06T18:22:54.661+0200 [DEBUG] provider.terraform-provider-kustomization_v0.5.0: 2021/10/06 18:22:54 JSONERRORmod:  unexpected end of JSON input
  26131,108: 2021-10-06T18:22:54.756+0200 [DEBUG] provider.terraform-provider-kustomization_v0.5.0: 2021/10/06 18:22:54 JSONERRORmod:  unexpected end of JSON input
  26142,108: 2021-10-06T18:22:55.174+0200 [DEBUG] provider.terraform-provider-kustomization_v0.5.0: 2021/10/06 18:22:55 JSONERRORmod:  unexpected end of JSON input
```

This made me think that I am passing an empty string to the manifest resource. It is not the case since I put the manifest content inside a `resource "local_file"` and the content is there:
```
{"apiVersion":"v1","kind":"Service","metadata":{"name":"appsmith-editor","namespace":"appsmith"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"appsmith-editor"}}}
```

That said, after all that, I (by instinct, as it was the only json encoded field I could see) tried to delete the `kubectl.kubernetes.io/last-applied-configuration` annotation from the resource and the plan magically started working.
All the resources I have inside that namespace have the same problem, and after removing the `kubectl.kubernetes.io/last-applied-configuration` annotation they all started working again.

Please, let me know if I can be of any additional help 🙏

**Comment by pst** [comment] 2021-10-08 09:36
Thanks for the clarification. What's your K8s version, maybe it's an issue stemming from the K8s api version and SDK version the provider uses.

**Comment by sirlori** [comment] 2021-10-08 11:15
@pst 
`Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`

Thanks for looking into this 🙏

**Comment by pst** [comment] 2021-10-08 12:23
@sirlori so one thing, if you removed the lastAppliedConfiguration annotation from the resource in the K8s api, the error is expected to happen every time. The provider can only handle resources that have the annotation at this time.

The bug I'm trying to hunt down in our case is, this error happening even though the resource has the annotation. Like it did in your case originally before you removed the annotation.

What I'm trying to find, is a way to reproduce how the issue happened the first time. Hope that explanation makes sense.

**Comment by pst** [comment] 2022-06-10 14:09
Closing this issue. We haven't seen it again since Oct last year. And there is no reproduction.

**Closed by pst** 2022-06-10 14:09 UTC
