### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in manifest.go v0.9.0

### ISSUE THREAD

**Issue by adamdecaf** [kbst/terraform-provider-kustomization#206] opened 2022-08-03 13:38 UTC
We ran into a panic with v0.9.0 of the kustomize provider when running on Terraform cloud. It was during an apply. Here's the stack trace:

```
Stack trace from the terraform-provider-kustomization_v0.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163ef36]

goroutine 15 [running]:
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).gvr(...)
github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:109
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).api(0xc000276ed0)
github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:151 +0x36
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).apiGet(0xc0005a6300?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}})
github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:171 +0x66
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).apiPreparePatch(0xc000276ed0, 0x198b201?, 0x0)
github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:201 +0x92
github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceUpdate(0x0?, {0x16c5f00?, 0xc0003b3b60})
github.com/kbst/terraform-provider-kustomize/kustomize/resource_kustomization.go:320 +0x3d2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1c375f0?, {0x1c375f0?, 0xc0001f4a80?}, 0xd?, {0x16c5f00?, 0xc0003b3b60?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000b87e0, {0x1c375f0, 0xc0001f4a80}, 0xc00080dc70, 0xc0000b2880, {0x16c5f00, 0xc0003b3b60})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000353ce0, {0x1c37548?, 0xc0000f7040?}, 0xc0005d8960)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00043d2c0, {0x1c375f0?, 0xc0001f42a0?}, 0xc000425d50)
github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18cfea0?, 0xc00043d2c0}, {0x1c375f0, 0xc0001f42a0}, 0xc000795020, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000230540, {0x1c3bb70, 0xc000291a00}, 0xc000365440, 0xc000639230, 0x285f6e0, 0x0)
google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000230540, {0x1c3bb70, 0xc000291a00}, 0xc000365440, 0x0)
google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-kustomization_v0.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by pst** [comment] 2022-08-03 19:17
Thanks for reporting. Do you have a manifest and kustomization to reproduce this?

**Comment by darwinz** [comment] 2022-08-08 15:36
I can jump in here - I'm on the same team as @adamdecaf, who added this issue.  

This error went away on a subsequent plan/apply, so it's no longer an issue for us, but I can shed a little light on when the issue appeared for us.

The error came up when applying an update to the `hashicorp/vault` helm chart.  We have the following patches, which patch the IP address subnet ranges that Kubernetes sets on the vault services.

```
  patches = [
    {
      target = {
        kind      = "Service"
        name      = "vault"
        namespace = kubernetes_namespace.vault.metadata[0].name
      }

      patch = [
        {
          op    = "add"
          path  = "/spec/loadBalancerSourceRanges"
          value = data.terraform_remote_state.cloud.outputs.network_ip_cidr_ranges
        }
      ]
    },
    {
      target = {
        kind      = "Service"
        name      = "vault-active"
        namespace = kubernetes_namespace.vault.metadata[0].name
      }

      patch = [
        {
          op    = "add"
          path  = "/spec/loadBalancerSourceRanges"
          value = data.terraform_remote_state.cloud.outputs.network_ip_cidr_ranges
        }
      ]
    },
    {
      target = {
        kind      = "Service"
        name      = "vault-standby"
        namespace = kubernetes_namespace.vault.metadata[0].name
      }

      patch = [
        {
          op    = "add"
          path  = "/spec/loadBalancerSourceRanges"
          value = data.terraform_remote_state.cloud.outputs.network_ip_cidr_ranges
        }
      ]
    }
  ]
}
```

The change that caused the error was changing the values from hard-coded slices of CIDR IP ranges to pulling the slices of CIDR IP ranges from a remote state data object as referenced above.

**Comment by pst** [comment] 2022-08-11 20:36
Thanks for adding more details. Unfortunately, I don't have an immediate idea what the root cause could be here. I'll leave this open to see if other people can add more details that help track this down.

**Comment by adamdecaf** [comment] 2022-08-12 12:51
No worries. We are not seeing the panic continue, so it was likely a temporary cause.

**Comment by pst** [comment] 2022-11-26 11:15
This has been open for a while and since it isn't a persistent issue and nobody else has reported it I will go ahead and close this for now. If you feel it's important to keep it open I am open to discuss.

**Closed by pst** 2022-11-26 11:15 UTC

**Comment by bschaeffer** [comment] 2023-08-01 15:41
Seeing this now

**Comment by bschaeffer** [comment] 2023-08-01 15:42
```
module.argocd.kustomization_resource.appproject_argocd_default: Modifying... [id=f77560ba-893c-4be6-8310-94793ca84074]
╷
│ Error: Plugin did not respond
│ 
│   with module.argocd.kustomization_resource.appproject_argocd_default,
│   on ../modules/argocd/main.tf line 252, in resource "kustomization_resource" "appproject_argocd_default":
│  252: resource "kustomization_resource" "appproject_argocd_default" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-kustomization_v0.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163ef36]

goroutine 97 [running]:
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).gvr(...)
	github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:109
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).api(0xc0005beed0)
	github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:151 +0x36
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).apiGet(0xc0005a9680?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}})
	github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:171 +0x66
github.com/kbst/terraform-provider-kustomize/kustomize.(*kManifest).apiPreparePatch(0xc0005beed0, 0x198b201?, 0x0)
	github.com/kbst/terraform-provider-kustomize/kustomize/manifest.go:201 +0x92
github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceUpdate(0x0?, {0x16c5f00?, 0xc0004c8ea0})
	github.com/kbst/terraform-provider-kustomize/kustomize/resource_kustomization.go:320 +0x3d2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1c375f0?, {0x1c375f0?, 0xc00024c9f0?}, 0xd?, {0x16c5f00?, 0xc0004c8ea0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00012ca80, {0x1c375f0, 0xc00024c9f0}, 0xc00022fad0, 0xc0005ac700, {0x16c5f00, 0xc0004c8ea0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000285bc0, {0x1c37548?, 0xc000290480?}, 0xc00012ae60)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00014fc20, {0x1c375f0?, 0xc00024c1e0?}, 0xc000444000)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x18cfea0?, 0xc00014fc20}, {0x1c375f0, 0xc00024c1e0}, 0xc0003a22a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000499dc0, {0x1c3bb70, 0xc0005829c0}, 0xc000596000, 0xc00023b8f0, 0x285f6e0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000499dc0, {0x1c3bb70, 0xc0005829c0}, 0xc000596000, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
```
